services:
  - type: web
    name: kirill's home website
    envVars:
      - key: NODE_VERSION
        value: 20.19.2
    buildCommand: git submodule update --init --recursive && npm install && npm run build
    staticPublishPath: ./dist
